name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm config set @kounta:registry https://lightspeedhq.jfrog.io/lightspeedhq/api/npm/npm-local/
          npm config set //lightspeedhq.jfrog.io/lightspeedhq/api/npm/npm-local/:_password \${NPM_ARTIFACTORY_PASSWORD}
          npm config set //lightspeedhq.jfrog.io/lightspeedhq/api/npm/npm-local/:username \${NPM_ARTIFACTORY_USER}
          npm config set //lightspeedhq.jfrog.io/lightspeedhq/api/npm/npm-local/:email ci@lightspeedhq.com
          npm config set //lightspeedhq.jfrog.io/lightspeedhq/api/npm/npm-local/:always-auth true
          npm ci
          npm publish
        env:
          NPM_ARTIFACTORY_USER: ls-kounta-dbjs-ci
          NPM_ARTIFACTORY_PASSWORD: ${{secrets.NPM_JFROG_BASE64_TOKEN}}
